[package]
name = "ai-sdk-provider"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Provider definition for AI SDK"
categories = ["api-bindings"]

[dependencies]
regex = "1.12.2"
async-trait = "0.1.89"
futures = "0.3.31"
serde_json = "1.0.145"
url = "2.5.7"
serde = { version = "1.0.228", features = ["derive"] }
