[package]
name = "ai-sdk-provider"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Provider definition for AI SDK"
categories = ["api-bindings"]

[dependencies]
